### ISSUE TITLE
Open source license?

### ISSUE THREAD

**Issue by Andrew67** [jasonlbeggs/tip-calculator#1]
Hi Jason,

Found this Tip Calculator via Appscope and have been using it since when out and about.
There's a few tweaks I'd love to make for (mainly) my own convenience, but I noticed there's no license specified for the code.
Are there any plans for licensing the code under an open source license?

Thanks!

**Comment by jasonlbeggs** [comment]
Hey @Andrew67! Sorry I didn't see this earlier. Fork it and do whatever you want with it. This was just a toy project for playing around with Vue PWAs and Tailwind.
